# Site settings
author: bruce willis
title: The journey into coding
header-img: img/home-bg.png
email: fashun_vyctum@yahoo.com
copyright_name: bruce willis
description: > # this means to ignore newlines until "baseurl:"
  A newbies journal
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  BruceBruce

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
